#!/bin/env node
// Generated by LiveScript 1.6.0
(function(){
  var args, ejson, chroma, fs, log, i$, ref$, len$, fname;
  args = process.argv.slice(2);
  ejson = require("ejson-mark").ejson;
  chroma = require('chroma');
  fs = require('fs');
  log = function(it){
    return console.log(chroma.cyan(it));
  };
  if (args[0] === "-p") {
    for (i$ = 0, len$ = (ref$ = args.slice(1)).length; i$ < len$; ++i$) {
      fname = ref$[i$];
      fs.writeFileSync(fname + ".json", ejson.toJSON(fname + ".ejson"));
    }
  } else if (args[0] === "-s") {
    for (i$ = 0, len$ = (ref$ = args.slice(1)).length; i$ < len$; ++i$) {
      fname = ref$[i$];
      ejson.stringify(JSON.parse(fs.readFileSync(fname + ".json")), fname + ".ejson");
    }
  } else {
    log(chroma.green("Ejson-Lang Command Line Tool V1.0.0"));
    log("  -h help");
    log("  -p <...fname> parse file to json");
    log("  -s <...fname> make json to ejson");
  }
}).call(this);
